# Generated by Django 5.2.6 on 2026-05-11 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_display', models.CharField(help_text='e.g. ₹1.2 Cr or ₹35,000 / mo', max_length=50)),
                ('price_amount', models.DecimalField(decimal_places=2, help_text='Numeric price for sorting/filtering', max_digits=15)),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=20)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Commercial', 'Commercial')], default='Apartment', max_length=20)),
                ('location', models.CharField(help_text='Specific area like Baner, Wakad', max_length=100)),
                ('area', models.CharField(choices=[('Pune', 'Pune'), ('PCMC', 'PCMC')], default='Pune', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('bhk', models.IntegerField(default=2)),
                ('bathrooms', models.IntegerField(default=2)),
                ('sqft', models.IntegerField(help_text='Total area in square feet')),
                ('furnishing_status', models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi-furnished', 'Semi-furnished'), ('Fully-furnished', 'Fully-furnished')], default='Unfurnished', max_length=30)),
                ('facing', models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South'), ('North-East', 'North-East'), ('North-West', 'North-West'), ('South-East', 'South-East'), ('South-West', 'South-West')], max_length=20, null=True)),
                ('property_age', models.CharField(blank=True, help_text='e.g. 0-5 years, Ready to move', max_length=50, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(default=False)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('lister_name', models.CharField(max_length=100)),
                ('lister_phone', models.CharField(max_length=15)),
                ('lister_role', models.CharField(default='Owner', help_text='Owner, Agent, etc.', max_length=50)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
