# Generated by Django 5.2.6 on 2026-06-24 12:35

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.CharField(choices=[('Hero', 'Main Photo'), ('Interior', 'Interior (Living/Bed/Kitchen)'), ('Exterior', 'Exterior (Building/Front)'), ('Amenities', 'Amenities (Gym/Pool/Garden)'), ('Map', 'Layout / Map'), ('Neighborhood', 'Neighborhood / Surroundings')], default='Interior', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
